backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use backend\models\HostSettings;
use backend\models\LogsSearchForm;
use backend\models\SystemLog;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'host-settings', 'logs', 'view-log', 'delete-log', 'delete-all-logs'],
                        'allow' => true,
                        'roles' => ['moderator'],
                    ],

                    [
                        'actions' => ['logout', 'index', 'host-settings',
                            'delete-setting', 'logs', 'view-log', 'delete-log', 'delete-all-logs'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'delete-setting' => ['post'],
                    'delete-log' => ['post'],
                    'delete-all-logs' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {

        $this->layout = 'backendLogin';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string
     */
    public function actionHostSettings()
    {
        $settings = HostSettings::find()->all();

        $hostSettings = [new HostSettings()];

        if (Model::loadMultiple($hostSettings, Yii::$app->request->post()) && Model::validateMultiple($hostSettings)) {

            foreach ($hostSettings as $setting) {

                $setting->save(false);
            }
            return $this->redirect('host-settings');
        }

        if (Model::loadMultiple($settings, Yii::$app->request->post()) && Model::validateMultiple($settings)) {

            foreach ($settings as $setting) {

                $setting->save(false);
            }
            return $this->redirect('host-settings');
        }


        return $this->render('host-settings', ['hostSettings' => $hostSettings, 'settings' => $settings]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws \ErrorException
     */
    public function actionDeleteSetting($id)
    {
        $setting = HostSettings::findOne($id);
        if (!$setting->delete()) {

            throw new \ErrorException('Ошибка удаления');
        }

        return $this->redirect('host-settings');
    }


    /**
     * @return string
     */
    public function actionLogs()
    {
        $logsSearch = new LogsSearchForm();

        $dataProvider = $logsSearch->search(Yii::$app->request->queryParams);

        return $this->render('logs', [

            'dataProvider' => $dataProvider,
            'logsSearch' => $logsSearch
        ]);

    }

    /**
     * @param $id
     * @return string
     */
    public function actionViewLog($id)
    {

        $log = SystemLog::findOne($id);

        return $this->render('view-log', ['model' => $log]);

    }

    /**
     * @param $id
     * @return \yii\web\Response
     */
    public function actionDeleteLog($id)
    {

        $log = SystemLog::findOne($id);

        $log->delete();

        return $this->redirect(['logs']);

    }

    /**
     * @return \yii\web\Response
     */
    public function actionDeleteAllLogs()
    {
        SystemLog::deleteAll();

        return $this->redirect(['index']);
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;



use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\helpers\Html;
use yii\helpers\VarDumper;
use \yii\helpers\HtmlPurifier;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\HttpException;
use \frontend\models\Chat;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup',],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],


                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * @param \yii\base\Action $action
     * @return bool|\yii\web\Response
     */
    public function beforeAction($action)
    {
        if ($action->id == 'contact') {

            return $this->redirect(['index']);
        }
        return parent::beforeAction($action);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {


        if (Yii::$app->request->isAjax) {

            $cleanMessage = HtmlPurifier::process(Yii::$app->request->post('message'));
            $cleanName = HtmlPurifier::process(Yii::$app->request->post('name'));
            $chat = new Chat();
            $chat->name = isset($cleanName) ? $cleanName : 'Гость';
            $chat->message= $cleanMessage;
            $chat->save();
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return $chat;
        }

        $chat = Chat::find()->all();
        return $this->render('index', ['chat' => $chat]);


    }

    /**
     * @throws HttpException
     */
    public function actionCleanChat()
    {
        if (!Yii::$app->request->isAjax) {
            throw new HttpException(400, 'Only ajax request is allowed.');
        }
        Chat::deleteAll();
        return;


    }

//    public function actionChat()
//    {
//        if (Yii::$app->request->isAjax) {
//
//            $cleanMessage = HtmlPurifier::process(Yii::$app->request->post('message'));
//
//            if (Yii::$app->session->get('chat') !== null) {
//                $chatMessages = Yii::$app->session->get('chat');
//                array_push($chatMessages, $cleanMessage);
//                Yii::$app->session->set('chat', $chatMessages);
//
//                return $cleanMessage;
//
//            } else {
//                $chatMessages = array();
//                array_push($chatMessages, $cleanMessage);
//                Yii::$app->session->set('chat', $chatMessages);
//
//                return $cleanMessage;
//            }
//        }
//
//    }


    /**
     * @return string
     */
    public function actionDocuments()
    {
        return $this->render('documents');
    }


    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Благодарим Вас за обращение к нам. Мы ответим вам как можно скорее.');
            } else {
                Yii::$app->session->setFlash('error', 'Произошла ошибка в процессе отправки сообщения.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {

        $form = new SignupForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {

            try {
                $form->signup($form);

                Yii::$app->session->setFlash('success', 'Вы зарегестрировались успешно!');

                return $this->goHome();


            } catch (\DomainException $e) {

                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());

            }

        }

        return $this->render('signup', [
            'model' => $form,
        ]);

    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Проверьте свою электронную почту для дальнейших инструкций.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Извините, мы не можем сбросить пароль для указанного адреса электронной почты.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль сохранен.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    /**
     * @return string
     */
    public function actionOffline()

    {
        return $this->render('offline');
    }


    /**
     * @return bool
     */
    public function actionPhpInfo()
    {

        return phpinfo();
    }

}

backend/views/site/delete-log.php
<?php
/**
 * Created by PhpStorm.
 * User: webndesign
 * Date: 11.05.20
 * Time: 20:48
 */

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/host-settings.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $hostSettings \backend\models\HostSettings */
/* @var $settings \backend\models\HostSettings */

$this->title = 'Настройки';
$this->params['breadcrumbs'][] = ['label' => 'Главная', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="address-create">
    <h4>Добавить новую настройку</h4>
    <div class="box">

            <?php $form = ActiveForm::begin(); ?>
            <?php
            foreach ($hostSettings as $index => $setting) {
                echo $form->field($setting, "[$index]name")->label($setting->name);
                echo $form->field($setting, "[$index]value")->label($setting->value);
                echo $form->field($setting, "[$index]status")->checkbox();

            }
            ?>

        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>

    <h4>Настройки</h4>
    <?php $formUpdate = ActiveForm::begin([
        'id' => 'formUpdate'
    ]); ?>
    <div class="table-responsive">
        <table class="table table-bordered" id="items">
            <thead>
            <tr style="background-color: rgba(42,0,49,0.33);">
                <th width="30%" class="text-left">Название</th>
                <th width="60%" class="text-left">Значение</th>
                <th width="5%" class="text-left">Статус</th>
                <th width="5%" class="text-left">Удалить</th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($settings as $index => $setting): ?>

                <tr id="addItem">

                    <td class="text-left"><?= $form->field($setting, "[$index]name"); ?></td>
                    <td class="text-left"><?= $form->field($setting, "[$index]value"); ?></td>
                    <td class="text-center"><?= $form->field($setting, "[$index]status")->checkbox(); ?></td>
                    <td class="text-center"><?= Html::a('', ['delete-setting', 'id' => $setting->id], [
                            'class' => 'glyphicon glyphicon-trash',
                            'data' => [
                                'confirm' => 'Вы уверены, что хотите удалить данную настройку?',
                                'method' => 'post',
                            ],
                        ]) ?></td>
                </tr>

            <?php endforeach; ?>

            </tbody>

        </table>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Административная часть';
?>
<div class="site-index">




</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните следующие поля для входа:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Вход', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/logs.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use \yii\grid\ActionColumn;
use \yii\helpers\StringHelper;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $logsSearch backend\models\LogsSearchForm */

$this->title = 'Логи';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-logs">

    <h1><?= Html::encode($this->title) ?></h1>
    <p>

        <?= Html::a('Удалить все логи', ['/site/delete-all-logs'],[
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить все логи?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' =>$logsSearch,
        'columns' =>[

            ['class' => 'yii\grid\SerialColumn'],
            'id',
           [
                   'attribute' => 'level',
                   'value'=> function($model){

                        if($model->level === 1){

                            return 'error';
                        }
                   }
           ],
            'category',
            'log_time:date',
            'prefix',

            [
                'attribute' => 'message',
                'value' => function ($model) {

                    return StringHelper::truncate($model->message, 100);
                }

            ],
            [
                'class' => ActionColumn::class,
                'template' => '{view}{delete}',
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'view') {
                        $url = Yii::$app->urlManager->createUrl(['/site/view-log', 'id' => $model->id]);
                        return $url;
                    }

                    if ($action === 'delete') {
                        $url = Yii::$app->urlManager->createUrl(['/site/delete-log', 'id' => $model->id]);
                        return $url;
                    }

                }

            ],

        ]
        ])?>


</div>

backend/views/site/view-log.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\SystemLog */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Логи', 'url' => ['logs']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="log-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>

        <?= Html::a('Удалить', ['/site/delete-log', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить этот элемент?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'level',
            'category',
            'log_time:date',
            'prefix',
            'message',
        ],
    ]) ?>

</div>