backend/models/MetersData.php
<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "meters-data".
 *
 * @property int $idmetersdata
 * @property int $user_id
 * @property int $watermeter_id
 * @property int $cold1
 * @property int $wmcold2
 * @property int $cold2
 * @property int|null $wmcold3
 * @property int|null $cold3
 * @property int $wmhot1
 * @property int $hot1
 * @property int $wmhot2
 * @property int $hot2
 * @property int|null $wmhot3
 * @property int|null $hot3
 * @property string $date
 * @property int $created_at
 * @property int $updated_at
 * @property int $created_by
 * @property int $updated_by
 *
 * @property User $user
 */
class MetersData extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'metersdata';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'watermeter_id', 'cold1', 'wmcold2', 'cold2', 'wmhot1', 'hot1', 'wmhot2', 'hot2', 'date', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'required'],
            [['user_id', 'watermeter_id', 'cold1', 'wmcold2', 'cold2', 'wmcold3', 'cold3', 'wmhot1', 'hot1', 'wmhot2', 'hot2', 'wmhot3', 'hot3', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            [['date'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'idmetersdata' => 'Idmetersdata',
            'user_id' => 'User ID',
            'watermeter_id' => 'ХВС1',
            'cold1' => 'Показания',
            'wmcold2' => 'ХВС2',
            'cold2' => 'Показания',
            'wmcold3' => 'ХВС3',
            'cold3' => 'Показания',
            'wmhot1' => 'ГВС1',
            'hot1' => 'Показания',
            'wmhot2' => 'ГВС2',
            'hot2' => 'Показания',
            'wmhot3' => 'ГВС3',
            'hot3' => 'Показания',
            'date' => 'Дата ',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата изменения',
            'created_by' => 'Создано',
            'updated_by' => 'Изменено',
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }


}

backend/controllers/MetersDataController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\MetersData;
use backend\models\MetersDataSearchForm;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MetersDataController implements the CRUD actions for MetersData model.
 */
class MetersDataController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MetersData models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MetersDataSearchForm();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MetersData model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing MetersData model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idmetersdata]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing MetersData model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * @return string
     */
    public function actionExportExcel()
    {
        $query = MetersData::find();

        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
            'sort' => [
                'defaultOrder' => [
                    'idmetersdata' => SORT_DESC,
                ],
            ]
        ]);


        return $this->render('export-excel', ['provider' => $provider]);

    }

    /**
     * @param $from_date
     * @param $to_date
     * @return string
     */
    public function actionSearchExportExcel($from_date, $to_date)
    {

        $query = MetersData::find()
            ->andFilterWhere(['>=', 'created_at', $from_date ? strtotime($from_date . '00:00:00') : null])
            ->andFilterWhere(['<=', 'created_at', $to_date ? strtotime($to_date . '23:59:59') : null]);


        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
            'sort' => [
                'defaultOrder' => [
                    'idmetersdata' => SORT_DESC,
                ],
            ]
        ]);
        return $this->render('search-export-excel', ['provider' => $provider, 'from_date' => $from_date, 'to_date' => $to_date]);

    }


    /**
     * Finds the MetersData model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MetersData the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MetersData::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/MetersDataController.php
<?php

namespace frontend\controllers;

use common\models\MetersData;
use common\models\User;
use frontend\models\MetersDataSearchForm;
use Yii;
use yii\base\ErrorException;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;


class MetersDataController extends Controller
{


    private $metersData;

    public function __construct($id, $module, MetersData $metersData, array $config = [])
    {
        parent::__construct($id, $module, $config);
        $this->metersData = $metersData;

    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['user', 'moderator', 'admin', 'profile'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],

                ],
            ],

        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $counters = $this->metersData->checkCounters();
        $searchModel = new MetersDataSearchForm();
        $provider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', ['provider' => $provider, 'searchModel' => $searchModel, 'counters' => $counters]);

    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $user = User::findOne(['id' => Yii::$app->user->id]);

        if(!isset($user->profile)){
            Yii::$app->session->setFlash('warning', 'Необходимо заполнить данные счётчиков воды');
            return $this->redirect(['water-meter/index']);
        }

        $this->metersData->fillData();

        if ($this->metersData->load(Yii::$app->request->post()) && $this->metersData->validate()) {

            try {
                $metersData = MetersData::createMetersData($this->metersData);
                Yii::$app->session->setFlash('success', 'Показания расхода воды успешно добавлены');
                return $this->redirect(['view', 'id' => $metersData->idmetersdata]);

            } catch (ErrorException $exception) {

                Yii::$app->errorHandler->logException($exception);
                Yii::$app->session->setFlash('error', 'Ошибка сохранения');
            }
        }

        return $this->render('create', ['model' => $this->metersData]);


    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->wmcold3 !== 0 && $model->wmhot3 !== 0) {

            $model->scenario = MetersData::SCENARIO_THIRD_COUNTER;

        } else {
            $model->twoCounters = true;
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            try {
                $this->metersData->edit($model);
                return $this->redirect(['view', 'id' => $id]);

            } catch (ErrorException $exception) {
                Yii::$app->errorHandler->logException($exception);
                Yii::$app->session->setFlash('error', 'Ошибка сохранения');
            }
            if (isset($model->errors)) {

                Yii::$app->session->setFlash('error', 'Ошибка валидации данных');

            }
        }

        return $this->render('update', ['model' => $model]);
    }

    /**
     * @param $id
     * @return MetersData the loaded model
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {

        if (($model = MetersData::findOne($id)) !== null) {

            return $model;
        } else {

            throw new NotFoundHttpException('Запрашиваемая страница не существует.');
        }
    }

    /**
     * @param $id
     * @return \yii\web\Response
     */
    public function actionDelete($id)
    {
        $metersData = $this->findModel($id);

        try {

            $this->metersData->remove($metersData);

        } catch (ErrorException $exception) {

            Yii::$app->session->getFlash('error', 'Ошибка удаления');
            Yii::$app->errorHandler->logException($exception);
        }


        return $this->redirect('index');
    }

    /**
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        $counters = $this->metersData->checkCounters();
        return $this->render('view', [
            'model' => $this->findModel($id),
            'counters' => $counters
        ]);
    }

    /**
     * @return string
     */
    public function actionExportExcel()
    {
        $query = MetersData::find()->where(['user_id' => Yii::$app->user->id]);

        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
            'sort' => [
                'defaultOrder' => [
                    'idmetersdata' => SORT_DESC,
                ],
            ]
        ]);

        return $this->render('export-excel', ['provider' => $provider]);
    }

    /**
     * @param $from_date
     * @param $to_date
     * @return string
     */
    public function actionSearchExportExcel($from_date, $to_date)
    {

        $query = MetersData::find()->where(['user_id' => Yii::$app->user->id])
            ->andFilterWhere(['>=', 'created_at', $from_date ? strtotime($from_date . '00:00:00') : null])
            ->andFilterWhere(['<=', 'created_at', $to_date ? strtotime($to_date . '23:59:59') : null]);


        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
            'sort' => [
                'defaultOrder' => [
                    'idmetersdata' => SORT_DESC,
                ],
            ]
        ]);
        return $this->render('search-export-excel', ['provider' => $provider, 'from_date' => $from_date, 'to_date' => $to_date]);

    }

    /**
     * @param $id
     * @param $self
     * @return mixed|null|string
     * @throws ErrorException
     */
    public function actionMetersDataEmail($id, $self)
    {
        $model = $this->findModel((int)$id);

        $user = User::findOne(['id' => Yii::$app->user->id]);
        $address = $user->address->address;
        $profile = $user->profile;
        $fullAddress = "Показания воды $address , кв {$profile->apartment}";

        try {
            Yii::$app->mailer->compose(['html' => 'metersDataEmail-html'],
                ['model' => $model, 'address' => $address, 'fullAddress' => $fullAddress])
                ->setTo(boolval($self) ? $user->email : Yii::$app->params['tsjEmail'])
                ->setFrom($user->email)
                ->setSubject($fullAddress)
                ->send();
            Yii::$app->session->setFlash('success', 'Письмо успешно отправлено!');
            return $this->redirect([
                'view',
                'id' => $id,
                'model' => $model
            ]);

        } catch (\Exception $exception) {
            Yii::error($exception->getMessage());
            Yii::$app->session->setFlash('warning', 'Ошибка отправки почты ' . $exception->getMessage());

        }
    }

}

frontend/views/meters-data/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \yii\jui\DatePicker;

/**@var $this \yii\web\View */
/**@var $model common\models\MetersData */
/**@var $form yii\widgets\ActiveForm */


?>

<div>
<div>
    <?php $form = ActiveForm::begin(['id' => 'metersData']) ?>
    <div class="col-md-6">

        <?= $form->field($model, 'watermeter_id')->textInput() ?>
        <?= $form->field($model, 'cold1')->textInput() ?>
        <?= $form->field($model, 'wmcold2')->textInput() ?>
        <?= $form->field($model, 'cold2')->textInput() ?>
        <?php if ($model->twoCounters !== true): ?>
            <?= $form->field($model, 'wmcold3')->textInput() ?>
            <?= $form->field($model, 'cold3')->textInput() ?>
        <?php endif; ?>
    </div>

    <div class="col-md-6">
        <?= $form->field($model, 'wmhot1')->textInput() ?>
        <?= $form->field($model, 'hot1')->textInput() ?>
        <?= $form->field($model, 'wmhot2')->textInput() ?>
        <?= $form->field($model, 'hot2')->textInput() ?>
        <?php if ($model->twoCounters !== true): ?>
            <?= $form->field($model, 'wmhot3')->textInput() ?>
            <?= $form->field($model, 'hot3')->textInput() ?>
        <?php endif; ?>
    </div>
    <?php if (\Yii::$app->request->getPathInfo() === 'meters-data/update') : ?>
        <div class="col-md-6">
            <?= $form->field($model, 'date')->widget(DatePicker::class,
                ['language' => 'ru', 'dateFormat' => 'php:Y/m/d'])->label('Дата') ?>
        </div>
  <?php endif; ?>
</div>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Сохранить' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end() ?>

</div>

frontend/views/meters-data/create.php
<?php

use yii\helpers\Html;

/**@var $this yii\web\View */
/**@var $model common\models\MetersData */

$this->title = 'Добавление показаний расхода воды';
$this->params['breadcrumbs'][] = ['label' => 'Показания воды', 'url' => 'index'];
$this->params['breadcrumbs'][] = $this->title;
?>

<div>
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', ['model' => $model]) ?>

</div>

frontend/views/meters-data/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use \yii\helpers\Url;
use \yii\jui\DatePicker;
use \yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $provider yii\data\ActiveDataProvider */
/* @var $searchModel \frontend\models\MetersDataSearchForm */
/** @var $counters */

$this->title = 'Показания воды';
$this->params['breadcrumbs'][] = ['label' => 'Показание воды', 'url' => 'index'];

$from_date = isset(Yii::$app->request->getQueryParam('MetersDataSearchForm')['from_date']) ? Yii::$app->request->getQueryParam('MetersDataSearchForm')['from_date'] : null;
$to_date = isset(Yii::$app->request->getQueryParam('MetersDataSearchForm')['to_date']) ? Yii::$app->request->getQueryParam('MetersDataSearchForm')['to_date'] : null;


$visible = null;
if ($counters === true) {
    $visible = false;
} else {

    $visible = true;
}

?>

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Внести показания воды', ['create'], ['class' => 'btn btn-primary',]) ?>
        <?= Html::a('Сохранить все данные в Excel', ['export-excel'], ['class' => 'btn btn-default']) ?>
    </p>

    <hr>
<?php $form = ActiveForm::begin(['action' => 'index', 'method' => 'get']); ?>
    <div class="row">
        <h4>Поиск по дате</h4>

        <div class="col-md-3">
            <?= $form->field($searchModel, 'from_date')->widget(DatePicker::class, ['language' => 'ru', 'dateFormat' => 'php:Y/m/d'])->label('Дата с') ?>
        </div>
        <div class="col-md-3">

            <?= $form->field($searchModel, 'to_date')->widget(DatePicker::class, ['language' => 'ru', 'dateFormat' => 'php:Y/m/d'])->label('Дата по') ?>
        </div>

        <?php if (isset($from_date) && isset($to_date)) : ?>
            <div class="col-md-3">
                <?= Html::a('Сохранить в Excel результат поиска', ['search-export-excel', 'from_date' => $from_date, 'to_date' => $to_date], ['class' => 'btn btn-default']) ?>
            </div>
        <?php endif; ?>
        <div class="col-md-3">
            <div class="form-group">
                <?= Html::submitButton('Найти', ['class' => 'btn btn-primary']) ?>
                <?=  Html::a("Сбросить", Url::toRoute(['/meters-data/index']), ['class' => 'btn btn-default']) ?>
            </div>
        </div>
    </div>

<?php ActiveForm::end(); ?>
    <hr>
<?= GridView::widget([
    'dataProvider' => $provider,
    'filterModel' => $searchModel,
    'rowOptions' => function ($model, $key, $index, $grid) {
        return [
            'onclick' => 'location.href="'
                . Url::to(['/meters-data/view', 'id' => $key,]) . '"',
            'onmouseenter' => "style='background-color:#dedede; cursor: pointer;'",
            'onmouseleave' => "style='background-color:'",
        ];
    },

    'columns' =>
        [

            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'watermeter_id',
                'contentOptions' => ['style' => 'background-color:#0027ff14'],
            ],
            'cold1',

            [
                'attribute' => 'wmcold2',
                'contentOptions' => ['style' => 'background-color:#0027ff14'],
            ],
            'cold2',
            [

                'attribute' => 'wmcold3',
                'contentOptions' => ['style' => 'background-color:#0027ff14'],
                'visible' => $visible

            ],

            [
                'attribute' => 'cold3',
                'visible' => $visible
            ],
            [
                'attribute' => 'wmhot1',
                'contentOptions' => ['style' => 'background-color:#FFA39229'],
            ],
            'hot1',
            'wmhot2',
            [
                'attribute' => 'wmhot2',
                'contentOptions' => ['style' => 'background-color:#FFA39229'],
            ],
            'hot2',
            [
                'attribute' => 'wmhot3',
                'contentOptions' => ['style' => 'background-color:#FFA39229'],
                'visible' => $visible

            ],
            [
                'attribute' => 'hot3',
                'visible' => $visible
            ],

            [
                'attribute' => 'date',
                'format' => ['datetime', 'php:d.m.Y']
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],


]);


?>

frontend/views/meters-data/update.php
<?php
use \yii\helpers\Html;

/**
 * @var  $this yii\web\View
 * @var $model common\models\MetersData;
 */
$this->title = 'Изменение показаний счётчиков воды указанных '.$model->date;
$this->params['breadcrumbs'][] = ['label' => 'Показания воды', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div>
    <h1><?= Html::encode($this->title)?></h1>
    <?= $this->render('_form', ['model' => $model])?>


</div>

frontend/views/meters-data/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use  frontend\widgets\grid\MetersDataDetailView;

/* @var $this yii\web\View */
/* @var $model common\models\MetersData */
/** @var  $counters */
$this->title = 'Показание воды';
$this->params['breadcrumbs'][] = ['label' => 'Показание воды', 'url' => 'index'];
$this->params['breadcrumbs'][] = $this->title;

$visible = null;
if ($counters === true) {
    $visible = false;
} else {

    $visible = true;
}

?>
<div>


    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->idmetersdata], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->idmetersdata], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить этот элемент?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Переслать на email', ['/meters-data/meters-data-email', 'id' => $model->idmetersdata, 'self' => true], [
            'class' => 'btn btn-success',]) ?>

        <?= Html::a('Переслать в ТСЖ', ['/meters-data/meters-data-email', 'id' => $model->idmetersdata, 'self' => false], [
            'class' => 'btn btn-warning',]) ?>
    </p>
    <?= MetersDataDetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'attribute' => 'watermeter_id',
                'contentOptions' => ['style' => 'background-color:#0027ff14'],
            ],
            'cold1',
            [
                'attribute' => 'wmcold2',
                'contentOptions' => ['style' => 'background-color:#0027ff14'],
            ],
            'cold2',
            [
                    'attribute' => 'wmcold3',
                'contentOptions' => ['style' => 'background-color:#0027ff14'],
                'visible' => $visible
            ],
            'cold3',
            [
                'attribute' => 'wmhot1',
                'contentOptions' => ['style' => 'background-color:#FFA39229'],
            ],
            'hot1',
            [
                'attribute' => 'wmhot2',
                'contentOptions' => ['style' => 'background-color:#FFA39229'],
            ],
            'hot2',
            [
                'attribute' => 'wmhot3',
                'contentOptions' => ['style' => 'background-color:#FFA39229'],
            ],
            'hot3',
            [
                'attribute' => 'date',
                'format' => ['datetime', 'php:d.m.Y H:i:s']
            ],
        ]
    ])
    ?>

</div>